### ISSUE TITLE
Weitere Erfahrungen mit Version 20.04.2

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#10]
Hi,

manche Einstellungsänderungen werden nicht wirklich gespeichert beim Verlassen der Anwendung. Ich habe z.B. in der Muon-Paketverwaltung ein paar Änderungen in der Anzeige vorgenommen (Anzeige der installierten Version, Breite der Felder "Status"/"Angefordert"). Diese Anpassungen bleiben nach dem snapshot nicht erhalten in ctbankix. Führe ich solche Änderungen in meiner Virtuellen Maschine aus, dann sind sie beim nächsten Start immer noch vorhanden.

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Keine Ahnung. Könnte daran liegen, dass Muon sudo-Rechte braucht und die Konfigurationsdaten nicht im Homeverzeichnis abgelegt werden, was mit in den Snapshot gesichert wird. Hast Du es denn herausfinden können? Dann einfach hier nochmal das Ticket aufmachen und posten. Danke Dir!
