### ISSUE TITLE
Fehlermeldungen NVIDIA

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#11]
**Während der Generietrung treten etliche Fehlermeldungen auf bzgl. NVIDIA. Beginnt vor Zeile 122 des Scriptes. Hier der Ausschnitt aus dem Protokoll:**

_./BUILD: 4: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-frontend.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 14: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-p2p.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 22: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-kthread-q.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 25: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-kthread-q-selftest.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 27: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-modeset-interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 32: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-report-err.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 35: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv_uvm_interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 122: scripts/genksyms/genksyms: not found
cc: error: nvidia-modeset/nvidia-modeset-linux.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
122128 blocks
./BUILD: 2: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-frontend.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 10: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-p2p.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 21: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-modeset-interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 25: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-report-err.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 29: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv_uvm_interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 137: scripts/genksyms/genksyms: not found
cc: error: nvidia-modeset/nvidia-modeset-linux.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
177440 blocks
./BUILD: 3: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-frontend.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 10: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-p2p.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 22: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-modeset-interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 24: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-report-err.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 28: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv_uvm_interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 137: scripts/genksyms/genksyms: not found
cc: error: nvidia-modeset/nvidia-modeset-linux.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
112808 blocks
./BUILD: 4: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-frontend.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 13: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-p2p.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 22: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-kthread-q.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 25: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-kthread-q-selftest.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 26: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-modeset-interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 29: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-report-err.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 34: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv_uvm_interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 133: scripts/genksyms/genksyms: not found
cc: error: nvidia-modeset/nvidia-modeset-linux.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
122130 blocks
./BUILD: 2: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-frontend.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 10: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-p2p.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 22: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-modeset-interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 25: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-report-err.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 30: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv_uvm_interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 137: scripts/genksyms/genksyms: not found
cc: error: nvidia-modeset/nvidia-modeset-linux.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
177096 blocks
./BUILD: 3: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-frontend.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 9: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-p2p.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 22: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-modeset-interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 24: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv-report-err.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 29: scripts/genksyms/genksyms: not found
cc: error: nvidia/nv_uvm_interface.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
./BUILD: 137: scripts/genksyms/genksyms: not found
cc: error: nvidia-modeset/nvidia-modeset-linux.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
dpkg-gencontrol: warning: Depends field of package linux-image-unsigned-5.8.0-45-generic: substitution variable ${shlibs:Depends} used, but is not defined
dpkg-gencontrol: warning: Depends field of package linux-modules-5.8.0-45-generic: substitution variable ${shlibs:Depends} used, but is not defined
dpkg-gencontrol: warning: Built-Using field of package linux-modules-5.8.0-45-generic: substitution variable ${linux:BuiltUsing} used, but is not defined
dpkg-gencontrol: warning: Depends field of package linux-modules-extra-5.8.0-45-generic: substitution variable ${shlibs:Depends} used, but is not defined
dpkg-gencontrol: warning: Depends field of package linux-buildinfo-5.8.0-45-generic: substitution variable ${shlibs:Depends} used, but is not defined
dpkg-gencontrol: warning: Built-Using field of package linux-buildinfo-5.8.0-45-generic: substitution variable ${linux:BuiltUsing} used, but is not defined
+ cd ../../
+ export 'PS4=$(CHECK)\n\n$(tput bold)$(tput setaf 7)$(tput setab 4)+ (${BASH_SOURCE}:${LINENO}):$(tput sgr0) '
+ PS4='$(CHECK)\n\n$(tput bold)$(tput setaf 7)$(tput setab 4)+ (${BASH_SOURCE}:${LINENO}):$(tput sgr0) '
[PASS]

+ (./ctbankix.sh:122): apt-get -y install build-essential debootstrap squashfs-tools genisoimage syslinux-common syslinux-utils
[PASS]_

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Ich hab das auch gesehen aber das Skript läuft trotzdem durch. Lasse es so. Danke fürs Melden!
