### ISSUE TITLE
newline unexpected ..... bei Ausführung beider Scripts ...

### ISSUE THREAD

**Issue by MichelleBr-66** [ctbankix-continuation-team/ctbankix-continuation#12]
Hi Ihr Lieben,
ich habe versucht, auf x86 (mit Lubuntu 18.04) und x64 (Lubuntu 20.04) die jeweiligen zugehörigen Scripts laufen zu lassen. Ich habe von Scripts keine Ahnung und auch noch recht Linux-unerfahren.

Bei beiden Scripts erschien jeweils:
michelle@VMLubuntu:~/built$ sudo sh ctbankix-continuation_Lubuntu_64_20.04.2.sh
ctbankix-continuation_Lubuntu_64_20.04.2.sh: 8: Syntax error: newline unexpected

Wie kann ich das lösen?
Danke und alles Liebe
Michelle

**Comment by Firefoxfan** [comment]
Hallo Michelle,

ist das Script denn ausführbar gewesen? Mit

sudo chmod +x prozedurname.sh

kann man es ausführbar machen.

Ansonsten schau nochmal auf 
https://www.heise.de/forum/c-t/Kommentare-zu-c-t-Artikeln/Sicheres-Online-Banking-mit-Bankix/Re-bankix-20-04-2-wie-geht-es-weiter/posting-38668223/show/

Da habe ich gerade mein aktuelles Script eingestellt.

Der Fehler kann auch damit zusammenhängen, wenn man das Script sich unter Windows heruntergeladen hat. Es kann dann gegebenenfalls fale Marierungen für Zeilenende und -umbruch enthalen. Es müsste ggf. ins utf-8-Format umgespeichert werden oder es einmal mit Notepad++ editieren und als Unix-Script-file-Format abspeichern.

Gruß
Werner

**Comment by MichelleBr-66** [comment]
Hallo Werner und dankeschön, dass Du mir helfen willst. *lächelt
Ich hatte Dir schon mal direkt per mail geantwortet, aber nicht darauf geachtet, dass es "noreply" ist. *schmunzelt

Die Datei war ausführbar gemacht und sie war tatsächlich unter Windows herunter geladen.
Nun habe ich Dein neues Script gleich versucht ... unter einem frisch installierten Lubuntu 20.04.2 x64 - aber beim Ausführen "meckert" das Script, dass die falsche Lubuntu-Version installiert sei?! Dabei IST es die richtige.

by the way - auch unter Lubuntu herunter geladen ergab das bisherige Script "newline unexpected" *schnief
Wird es denn auch noch ein Script für x86 geben? Ich würde mir gerne einen Stick mit beiden Versionen machen, mit dem man auch unterwegs sein kann und unabhängig ist von der jeweils vorhandenen Hardware.

Was kann ich noch machen?
Danke und alles Liebe
Michelle

**Comment by Firefoxfan** [comment]
Hallo Michelle,

es wird seit den 20er-Versionen keine Unterstützung mehr für x86 geben. Da sind nur noch ältere Versionen generierbar.

Diese Fehlermeldungen ".... falsche Version ..." haben mich auch schon geärgert. Das lässt sich aber ganz einfach umgehen.
Setze einfach in den Zeilen 33 - 42 ein # an den Beginn der Zeile, dann sind diese auskommentiert und diese Prüfung findet nicht statt. Sieht dann so aus:

# if [[ $questionResponse != [jJ] ]]
# then
#	exit
# fi
# if ! head -1 /etc/issue | grep -q 'Ubuntu 20.04.2' || ! [ $(getconf LONG_BIT) == '64' ]
# then
#	echo "Sie benutzen die falsche (L)Ubuntu-Version. Bitte (L)Ubuntu 20.04.2 64 Bit verwenden."
#	exit
# fi

Du kannst auch nochmal versuchen aus dem frisch installierten Lubuntu 20.04.2 über den Firefox das Script herunterzuladen. Dann sollte es eigentlich keine Probleme geben. Ich markiere mir dabei das komplette Script und kopiere es in die Zwischenablage. Dann lege ich eine leere Textdatei an und kopiere den Inhalt der Zwischenablage hinein.

Versuch mal dein Glück

Gruß
Werner

**Comment by Firefoxfan** [comment]
... irgendwo sind mein "#" (Nummernkreuze) entschwunden. Vor jede Zeile und eine Leerstelle.

**Comment by MichelleBr-66** [comment]
Meinst Du diese Zeilen?

![grafik](https://user-images.githubusercontent.com/81960410/114033725-c9dd7580-987d-11eb-9b67-a4fbcfe69baa.png)

**Comment by Firefoxfan** [comment]
Hallo Michelle,

also das da oben kann ich absolut nicht nachvollziehen, was da steht. Was hast du da verbrochen?
Jedenfalls ist das nicht das Generierungs-Script. ;-)
Gruß
Werner

**Comment by MichelleBr-66** [comment]
*huch...?
Habe ich jetzt für diesen thread was Falsches kopiert? *wundert sich.....
Nö - das ist eine der sh-Dateien, die ich heruntergeladen habe. Das ist ja komisch.....

**Comment by MichelleBr-66** [comment]
So - nachdem ich nun gemerkt habe, dass der Download im Firefox irgendwie (?) die Scripts verbogen hat, habe ich deren Inhalt händisch in ein Script gepackt und laufen lassen. 
Es lief eine Weile - dann brach es wie folgt ab:

".................ebug: install-doc
Debug: install-source
install -d /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/linux-source-5.8.0/usr/src/linux-source-5.8.0
Debug: /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/stamps/stamp-prepare-perarch
rm -rf /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/build/tools-perarch
install -d /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/build/tools-perarch
rsync -a --exclude debian --exclude debian.master --exclude debian.hwe-5.8 --exclude .git -a ./ /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/build/tools-perarch/
rsync: write failed on "/home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/build/tools-perarch/kernel/locking/rwsem.c": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]
make: *** [debian/rules.d/2-binary-arch.mk:662: /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/stamps/stamp-prepare-perarch] Fehler 11
Debug: /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/stamps/stamp-prepare-perarch
rm -rf /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/build/tools-perarch
install -d /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/build/tools-perarch
rsync -a --exclude debian --exclude debian.master --exclude debian.hwe-5.8 --exclude .git -a ./ /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/build/tools-perarch/
rsync: write failed on "/home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/build/tools-perarch/lib/Kconfig.debug": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]
make: *** [debian/rules.d/2-binary-arch.mk:662: /home/michelle/built/kernel/linux-hwe-5.8-5.8.0/debian/stamps/stamp-prepare-perarch] Fehler 11
tac: /tmp/tacbUplzZ: Schreibfehler: Auf dem Gerät ist kein Speicherplatz mehr verfügbar
debian/rules.d/0-common-vars.mk:15: *** Das erste Argument für  die „word“-Funktion muss größer als 0 sein.  Schluss.
bankix.run: 104: function: not found
[FAIL]
bankix.run: 112: Syntax error: "}" unexpected
"

*seufz

**Comment by Firefoxfan** [comment]
Versuch den Download des Scriptes doch mal so wie es in der Einleitung auf github beschrieben wird innerhalb deiner virtuellen Lubuntu-Maschine. Habe ich geringfügig auf die passende Version 20.04.2 geändert! 

Öffne ein Terminal und gib ein:

wget https://github.com/ctbankix-continuation-team/ctbankix-continuation/raw/master/ctbankix-continuation_Lubuntu_64_20.04.2.sh

chmod +x ctbankix-continuation_Lubuntu_64_20.04.2.sh

Dann kopierst du das Script in deinen Generierungsordner und startets es dort mit:

sudo ./ctbankix-continuation_Lubuntu_64_20.04.2.sh

**Comment by Firefoxfan** [comment]
Hallo Michelle,

wir sollten dann unsere Diskussion über den richtigen Verlauf besser auf der Forum-Seite c't fortführen. Es interessiert ja vielleicht auch andere Nutzer.

https://www.heise.de/forum/c-t/Kommentare-zu-c-t-Artikeln/Sicheres-Online-Banking-mit-Bankix/forum-31485/

Gruß
Werner

**Comment by MichelleBr-66** [comment]
Hallo lieber Werner,
mit der Erstellung hat es dann doch noch alles geklappt - deswegen schreibe ich hier. 
Ich danke Dir so sehr, dass Du mir geholfen hat. Warum Firefox nun die Scripte so verbogen hat .... wer weiß....

Ich würde dann im ct-Forum noch Fragen zur 32bit-Versionen besprechen wollen. Ist das ok?

Danke Dir noch einmal sehr .... alles Liebe für Dich

Michelle

**Comment by ctbankix-continuation-team** [comment]
Alles geklärt? Schließe das Ticket.
