### ISSUE TITLE
Anpassung Anleitung

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#13]
Hallo Christian,

auf der Startseite in github und im Script selbst sind noch eoin paar Textanpassungen in der Anleitung  erforderlich bzgl. Version 20.04.2 und zum zu verwendenden USB-Stick (2 - 4 GB). Die Größe des USB-Sticks ist spätestens nach einem Snapshot kaum noch ausreichend. Da solltest du eher >= 8 GB empfehlen.

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Danke, erledigt!
