### ISSUE TITLE
Aktueller Test-Status

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#14]
Hallo Christian,

ich habe gerade mal die neueste Version getestet. Dabei ist mir aufgefallen:

1. NVME-Drives tauchen nicht mehr auf. Problem gelöst.
2. Firefox enthält weiterhin das add-on "https everywhere". Dieses wird nicht mehr benötigt, ist über die Einstellungen selbst konfigurierbar.
3. Die gerade aktuellen Systemupdates "distro-info" und "ubuntu-advantage-tools" zerstören das System.
    a) nach dem Update (problemlos) erzeuge ich einen Snapshot und starte ctbankix neu.
    b) der Bildschirm hat dann einen komplett schwarzen Hintergrund
    c) BankixCreateSnapshot ist nicht mehr lauffähig / ausführbar.
4. Ohne diese alktuellen Updates lässt sich das System komplett weiterkonfigurieren und die Zwischenstände per Snapshot sichern.
5. Die Sicherung der Einstellungen von Muon und auch dem Dateimanager scheint jedenfalls nicht im Home-Verzeichnis zu erfolgen. Die Einstellungen werden beim Snapshot nicht übernommen. Wie/wo/was/warum konnte ich nicht feststellen.
6. Ich habe den Eindruck, dass es von Version zu Version schwieriger wird die passenden Komponenten zu finden und in das Script einzubinden. Schade, dass man offenbar bei der Erstellung der Ubuntu-Derivate solche Probleme hat. Damit müssen wir wohl leben und uns damit dann auf die jeweiliger 1er-Version beschränken.

Vorab schon mal vielen Dank für deine Mühe.

Gruß
Werner

**Comment by Firefoxfan** [comment]
Als kleine Ergänzung zu Pkt. 3:

Nachdem ich mein System dann ohne die beiden Updates fertig konfiguriert habe (Oberfläche nach meinem Geschmack angepasst, Atril/Clam-Tk/Thunderbird/ttf-mscorefonts/Drucker nachinstalliert und Kleinigkeiten deinstalliert) und diverse Banking-Arbeiten problemlos durchgeführt habe, habe ich mich heute morgen getraut und ndie beiden Updates eingespielt. 

Siehe da, keine Probleme, der Snapshot läuft problemlos durch.

Bitte nicht fragen wieso. :-(

Gruß
Werner

**Comment by Firefoxfan** [comment]
Ergänzung zu Pkt. 5:

Die geänderten Einstellungen werden jetzt durch den Snapshot übernommen.

Gruß
Werner

**Comment by Firefoxfan** [comment]
Hallo Christian,
eine kleine Idee. Nach dem Booten vom Stick steht ctbankix im Grub-Auswahlmenü und wartet auf meine Anwort (Enter) um das eigentliche System zu starten. Mir wird wg. UEFI nur ein System zur Auswahl angeboten.

Gibt es die Möglichkeit dem Grub-Menü ein Timeout zu verpassen? Vielleich so 5 Sekunden?

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Firefoxfan,

das müsste gehen und zwar in der grub.cfg. Vergleiche das mal mit der eines installierten Ubuntus. Dort ist es ja auch gesetzt. Kannst mir gern mal Rückmeldung geben, dann übernehme ich das ggf mit.

VG, Christian!

**Comment by Firefoxfan** [comment]
Habe ich in dem anderen Issue bei den Testergebnissen dokumentiert.
Ist anpassbar mit set timeout=10

Werner
