### ISSUE TITLE
Secure Boot

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#15]
Hallo,

wenn "Secure Boot" mit "Windows UEFI Mode" im BIOS (aktuelles BIOS für ASUS PRIME X570-Pro) aktiviert ist, dann kann zwar der USB-Stick zum Booten ausgwählt werden und es erscheint auch das Grub-Menü zur Auswahl des CTBankix.

Nach Auswahl erscheint jedoch die Fehlermeldung "./casper/vmlinuz has invalid signature" und es kann nicht weiter gebootet werden. CTBankix wird nicht geladen.

Das Standard-Lubuntu-20.04.2.iso startet problemlos vom USB-Stick. Tauscht man bei vmlinuz-Dateien aus, dann läuft auch CTBankix (jedoch nicht ganz so wie ursprünglich konfiguriert). Auch wenn ich im BIOS statt "Windows UEFI Mode" wieder "Other OS" einstelle geht es ja problemlos.

Da sollte doch in der Gerierungsprozedur ein signiertes vmlinuz eingebunden werden, damit der volle BIOS-Schutz gewährleistet werden kann.

Wie und wo muss etwas angepasst werden? Ich konnte da nichts erkennen.

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Firefox-Fan,

da weiß ich aktuell auch nicht weiter. Herr Dölle hatte das ja mal beschrieben und es hat wohl auch eine Zeit lang funktioniert aber woran das jetzt liegt - keine Ahnung. Bist Du da schon weiter gekommen?

VG, Christian!

**Comment by Firefoxfan** [comment]
Hallo Christian,

nein, tut mir leid, ich bin da nicht weitergekommen. Nur das Deaktivieren von secure-boot im BIOS hat mir geholfen. Müssen wir evtl. auf Ubuntu umsteigen? Dafür scheint ja ein Crypto-Key im UEFI hinterlegt zu sein. Wir generieren ja offenbar einen neuen Kernel für ctbankix, doch wie man da den Key bei der Generierung hinzufügen kann .... ? Keine Ahnung!

Gruß
Werner
