### ISSUE TITLE
Anpassungen Generierungsprozedur

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#17]
Hallo,

das hinterlegte Script zur Erstellung eines aktuelle ctbankix passt nicht mehr zu den vorhandenen Datenbeständen.

    Debian-HWE-5.8 scheint nicht mehr zu exixtieren. Und wenn, dann soll es mit dem linux-HWE-5.11 kombiniert werden?
    Die live.iso ist nicht richtig lauffähig.

Eine Anpassung an die aktuellen Gegebenheiten/Datenbestände ist wohl erforderlich.

Gruß
Werner

**Comment by Firefoxfan** [comment]
Ergänzung:

Beim Booten des neuen Systems erscheint eine Fehlermeldung:
[ 1.137151] gpio gpiochip1: (gpio_aaeon): tried to insert a GPIO chip with zero lines
[ 1.137161] gpiochip_add_data_with_key: GPIOs 0..-1 (gpio_aaeon) failed to register, -22

Nach den eigenen Anpassungen sind die Windows-Laufwerke wieder sichtbar.

**Comment by ctbankix-continuation-team** [comment]
Hallo Firefox-Fan,

Danke für Deine Hinweise! Ein neues Skript steht bereit. Ich lasse den Kernel dort aber noch auf Version 5.4. Ende Februar 2022 ist bereits ein neues Point-Release geplant. Wenn es mir gelingt, den neuen 5.15er Kernel anzupassen, dann stelle ich das neue Skript bereit.

VG, Christian!
