### ISSUE TITLE
Lubuntu 64 Bit 20.04.2 nicht mehr verfügbar

### ISSUE THREAD

**Issue by ChristianConradi** [ctbankix-continuation-team/ctbankix-continuation#18]
Hi,

ich bin schon früher ein Fan von CTBankix gewesen. Ich möchte gerne einen USB Stick mit Ihrer neuen Version erstellen.
Allerdings kann ich Lubuntu 64 Bit 20.04.2 nicht mehr finden. Ihr Link ist tot, alle anderen Seiten bieten eigentlich nur noch Lubuntu 64 Bit 20.04.3 an.
Leider blockiert Ihre Software 20.04.3 als ungültig.
Können Sie hier die Versionen anpassen und vielleicht einen Test auf die Patch-Version ganz rausnehmen?

Vielen Dank,

**Comment by Firefoxfan** [comment]
Hallo Christian,

schön, dass sich mal jemand für ctbanix auf den aktuellen Lubuntu-Versionen interessiert. Ich (Anwender und kein Linux-Sachverständiger!!!!!!) frage da zwar schon länger mal nach, doch irgendwie finde ich wohl nicht die richtigen Ansprechpartner. Es ist wohl nicht trivial die Generierungsprozedur immer wieder an die neuesten Versionen anzupassen.
Mir ist es aber gelungen eine ctbankix-Version unter Lubuntu 20.04.3 zu erzeugen. Dazu sind folgende Schritte - abweichend von der Beschreibung - erforderlich gewesen:
    1. Im Source-Verzeichnis muss die ISO-Datei von Lubuntu 20.04.3 stehen.
    2. In der Original-Prozedur für Version 20.04.2 sind per Editor alle Bezüge auf „20.04.2“ zu ersetzen durch „20.04.3“.
    3. Der fehlerhafte Abschnitt (Zeile 36 – 40) zum testen der verwendeten Version ist auszukommentieren durch 
        Voranstellen eines „# “-Zeichens (Nummernkreuz und Leerstelle). Dann entfällt diese Prüfung. Sieht dann so aus: 
        
        # if ! head -1 /etc/issue | grep -q 'Ubuntu 20.04.3' || ! [ $(getconf LONG_BIT) == '64' ]
        # then
        #	echo "Sie benutzen die falsche (L)Ubuntu-Version. Bitte (L)Ubuntu 20.04.3 64 Bit verwenden."
        #	exit
        # fi

    4. Die geänderte Prozedur dann abspeichern und starten.
    5. Es werden zwar noch Fehler auftreten/angezeigt wohl auch wg. des nicht mehr vorhandenen Bezugs auf „debian.hwe-5.8“, 
       doch die Prozedur läuft durch und erstellt eine live.iso mit ca. 1,6 GB und Kernel-Version 5.13.
    6. Diese wie gewohnt auf den USB-Stick bringen, booten und dann anpassen. Ob sie fehlerfrei ist kann ich nicht sagen! Sie 
        funktioniert jedenfalls.
    7. Der Ausschluss der modernen M2-NVME-SSDs ist nicht mehr enthalten, wohl wegen Pkt. 5, kann aber wieder nachgebaut 
        werden durch Anpassen der Startprozedur von Lubuntu.
Bessere/zusätzliche Informationen findest du im Forum auf heise.de bei

https://www.heise.de/forum/c-t/Kommentare-zu-c-t-Artikeln/Sicheres-Online-Banking-mit-Bankix/forum-31485

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Werner, hallo Christian,

super Vorarbeiten - Danke! Ich hab eine aktuelle Version bereitgestellt. Bitte mal testen und mir ggf. Feedback geben. Da Ubuntu keine alten ISOs mehr bereitstellt, muss ich das Skript wohl auch für neue Point-Releases anpassen. Also bereits wieder Ende 02/2022.

VG, Christian!

**Comment by Firefoxfan** [comment]
Hallo Christian,
ich werde mein Glück mal versuchen.

Gruß
Werner

**Comment by Firefoxfan** [comment]
Hallo Christian,

der erste Test war (fast) erfolgreich:

1. Fehler in Zeile 136 (wohl versehentlich), Abschnitt - >>>>> Kernel bauen <<<<< - enthält keinen ausführbaren Befehl. 
    In meiner Unkenntnis habe ich die Zeile mal so geändert:
    
    LANG=C skipabi=true skipmodule=true fakeroot debian/rules clean
    
    Danach läuft die Prozedur durch und erzeugt ein live.iso.
    
2. Der 1. Start von ctbankix zeigt keine Festplatten-Laufwerke und keine NVME-SSDs. Einzig eine zusätzlich per USB 
    angeschlossene externe HDD ist verfügbar. Das ist so richtig.
    
    Nach dem Systemupdate und Snapshot mit Neustart werden die NVME-SSDs wieder angezeigt. Das ist falsch.
    
3. Der 1. Start von Firefox zeigt die beiden Profile (relaxed und maximum hardened) zur Auswahl. Ich habe zu dem Zeitpunkt
    maximum gelöscht und relaxed ausgewählt. FX startet dann weiter. Kann aber nach Beenden nicht mehr gestartet werden. 
    Erst ein Snapshot mit Neustart löst das Problem.
    
4. Alle meine weiteren Anpassungen und Nachinstallationen konnten problemlos durchgeführt werden. 

5. Das System läuft bis auf den Fehler bzgl. der NVME-SSDs gut. Wobei Kernel 5.4 nicht so ganz doll ist, denn Lubuntu 20.04.3 
    läuft ja schon auf Kernel 5.13.

6. Gut fände ich eine Standardanpassung bei der Generierung evtl. zusätzliche Maus-Cursor mit zu installieren, z.B. 
    chameleon-cursor-theme. Das bietet mir die einzige Möglichkeit die Größe des Maus-Cursors auf meinem Bildschrirm
    (3840 x 2160) erkennbarer zu machen.
    Evtl. sinnvoll könnte auch die zusätzliche Installation bei der Generierung von Thunderbird für Kommunikationszwecke mit
    der Bank sein.

7. Wg. timeout muss ich noch gucken. 

8. Offen ist, wenn ich das richtig sehe) das Thema Kernel, denn offenbar wird ein unsignierter/signierter erzeugt, der (natürlich?) 
    kein secure-boot zulässt. Kann das die Ursache für das "secure-boot-Problem" sein?

Gruß
Werner

**Comment by Firefoxfan** [comment]
Hallo Christian,

zur Anpassung des timeout musst du den Abschnitt # Boot mit UEFI # ändern. Zeile 319 (set timeout=10) hinzufügen. Das sieht dann so aus:
# Boot (mit UEFI)
cat > iso/boot/grub/grub.cfg << EOF
if loadfont /boot/grub/font.pf2 ; then
	set gfxmode=auto
	insmod efi_gop
	insmod efi_uga
	insmod gfxterm
	terminal_output gfxterm
fi
set menu_color_normal=white/black
set menu_color_highlight=black/light-gray
set timeout=10
menuentry "c't Bankix Lubuntu ${UBUNTU_VERSION}" {
	set gfxpayload=keep
	linux	/casper/vmlinuz boot=casper fsck.mode=skip showmounts quiet splash noprompt -- debian-installer/locale=de_DE console-setup/layoutcode=de
	initrd	/casper/initrd.lz
}
EOF
# <<<<< Boot-Menue <<<<<

Gruß
Werner

**Comment by Firefoxfan** [comment]
Hallo Christian,

**Fehler im Script:** 

In deinem Script hier hier auf Github sieht die Zeile 136 so aus:

**LANG=C fakeroot debian/rules clean**

Bei der Ausführung wird bemängelt, dass sie keinen Befehl enthält. Erst nach Änderung auf:

**LANG=C skipabi=true skipmodule=true fakeroot debian/rules clean**

(entsprechend den nachfolgenden Zeilen, habe ich mal so vermutet) läuft das Script richtig durch.

Ich weiß aber nicht, was das ansonsten noch bewirkt haben könnte.

**M2-NVMEs:** 
Das angepasste Script habe ich noch mehrmals z.B. mit Anpassung des timeout-Parameters durchlaufen lassen. Jedesmal nach dem Update des gebooteten Systems sind die M2-NVMEs wieder sichtbar. Nur beim ersten Booten des jungfräulichen Systems sind sie nicht vorhaben. Ein nachfolgendes Snapshot ohne Durchführung von Updates bietet ein neues ctbankix ohne M2-NVMEs.

Gruß
Werner

**Comment by Firefoxfan** [comment]
Hallo Christian,

ich habe den Test mit deinem Script nochmal wiederholt. Es ist durchgelaufen. Ich muss also vorher irgendetwas vermurkst haben. Tut mir leid.

Allerding besteht das Problem mit den M2-NVMEs nachwievor. Nach dem Update werden diese wieder sichtbar. Für das Update werden folgende Komponenten angeboten:

libsmbclient
libwbclient0
linux-headers-5.4.0-96-generic
linux-modules-5.4.0-96-generic
linux-modules-extra-5.4.0-96-generic
python3-ldb
samba-libs

Wenn ich die aktualisiere erscheinen danach wieder die M2-NVMEs wieder im Dateimanager. Sollten nicht die Linux-Komponenten bereits bei der Generierung enthalten gewesen sein?

Meine eigenen Anpassungen (ohne die Updates durchgeführt zu haben) kann ich problemlos durchführen.

Gruß
Werner

**Comment by Firefoxfan** [comment]
Hallo Christian,

auch eine komplette Neuinstallation meiner VM (Virtual-Box 6.1.32 mit Lubuntu 20.04.3) mit anschließenden Updates und danach Generierung eines neuen ctbankix führt immer noch zu dem Fehler der sichtbaren M2-NVMEs. Die Generieung ergibt ein System ohne NVMEs und nach den Updates und snapshot mit Reboot sind die M2-NVMEs wieder sichbar.

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Werner,

ich konnte Dein Problem bei mir leider nicht reproduzieren. Lediglich

libsmbclient
libwbclient0
samba-libs

wurden bei einem Update bei mir nachinstalliert.

Probier mal bitte das von der Pipeline hier auf Github gebaute ISO-Image unter [Releases](https://github.com/ctbankix-continuation-team/ctbankix-continuation/releases). Es wird mit dem aktuellen Skript gebaut und auch dort werden nur die drei oben aufgeführten Pakete bei einem Update nachgeladen, nicht jedoch die linux-*-Pakete aus Deinem Kommentar.

Viele Grüße
Christian

**Comment by Firefoxfan** [comment]
Hallo Christian,

ich hatte in meinen Ordner zum Starten der Generierungsprozedur noch einen Unterordner "source" in dem bereits das aktuelle "lubuntu_20.04.3.iso" vorhanden war. (siehe altes Script, um den zeitaufwändigen Doenload einzusparen). Als ich diese Datei einfach gelöscht habe hatte ich plötzlich auch nur noch 3 Aktualisierungen und das Thema M2-NVME war okay. Wieso das dann geklappt hat wäre eine sehr gute Frage auf die ich keine Antwort habe.

Allerdings habe ich heute nochmal eine Erstellung mit deinem aktuellen Script und exakt deiner Beschribung durchgeführt. Das Ergebnis ist nicht gut, NVME = o.k., jedoch ein dritters "snapshot" geht nicht mehr.
Ich habe dann mal dein neues .iso herunter geladen. Der Start ist o.k., Snapshot klappt, Reboot ist okay. Jedoch ist der Hintergrund da schon schwarz, NVME istr o.k., ein zweiter "snapshot" geht jedoch nicht mehr. Es ist also keine weitere Anpassung möglich.

Gruß
Werner

**Comment by Firefoxfan** [comment]
Hallo Christian,

ich habe noch eine Weile mit deinem Script diverse Versuche gemacht, doch nicht wirklich erfolgreich.

Dann habe ich dein Original-ISO vom 16.02. heruntergeladen und unter W10 mit unetbootin auf einen frisch formatierten Strick geschrieben. 
Testergebnisse:
1. Der Bootvorgang ist okay, angezeigt wird der Standard-Desktophintergrund von Lubuntu mit einigen Symbolen (Firefox, Snapshot etc.).
2. M2-NVMEs werden nicht angezeigt!
3. Ich ändere absolut nichts.
4. Der abschließende Snapshot läuft erfolgrich durch. 
5. Der neue Bootvorgang ist o.k., der Standarddesktop hat von sich aus gewechselt auf schwarzen Hintergrund.
6. M2-NVMEs sind nicht sichtbar.
7. Snapshot kann nicht ausgeführt werden. Fehlermeldung: "Failed to execute child process xterm"
8. Ende des Tests

Vermutungen kann ich nicht äußern, läuft eben nicht.

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Werner,

die Erstellung des Snapshots habe ich angepasst. Es wird jetzt hoffentlich auch immer gewartet, bis alle Daten auf den Stick geschrieben wurden. Zuvor sind natürlich alle Fenster zu schließen und während der Erstellung des Snapshots darf man nichts weiter machen. Probier es mal aus.

VG
Christian
