### ISSUE TITLE
Lubuntu 20.04.4 ctbankix-Generierung mit aktuellem Script

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#19]
Hallo zusammen,

ich habe mir unter VirtualBox eine neue Maschine erstellt mit Lubuntu 20.04.4. Die Generierungsprozedur habe ich geringfügig angepasst auf 20.04.4 und eine Generierung mit folgenden Ergebnissen gestartet:

1. Die Prozedur läuft (anscheinend) einwandfrei durch, das erzeugte ISO mit Kernel 5.4(!) ist startfähig.
2. Alle internen Festplatten/Laufwerke incl. M2-NVMEs sind ausgeblendet.
3. Alle (meine) Anpassungen konnte ich erfolgreich durchführen.
4. Der Snapshot (mehrfach mal durchgeführt) läuft einwandfrei. Die neu erstellten Syteme enthalten die durchgeführten Änderungen
    und laufen.
5. Ruft man allerdings über die Muon-Paketverwaltung ein UPDATE des Systems auf werden folgende Komponenten angeboten:

    command-not-found
    fwupd
    libfwupdplugin5
    libjavascriptcoregtk-4.0-18
    libopengl0
    libwebkit2gtk-4.0-37
    linux-firmware
    linux-headers-5.4.0-104-generic
    linux-modules-5.4.0-104-generic
    linux-modules-extra-5.4.0-104-generic
    python3-commandnotfound
    
6. Der Update läuft problemlos durch und der anschließende Snapshot erzeugt wieder ein bootfähiges System.
7. In dem neuen System werden nach dem Booten wieder M2-NVME-Laufwerke angezeigt. 
    Samsung SSD 970 EVO Plus 250 GB (GPT-formatiert, Laufwerk C:)
    Samsung SSD 970 EVO Plus 500 GB (GPT-formatiert, Laufwerk D: und E:)
8. Die Laufwerke lassen sich durch Anpassung der Startprozedur zwar wieder ausblenden, doch das ist so eigentlich nicht gewollt.

Soweit mal die aktuellen Testergebnisse. 

Gruß Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Werner,

Danke für Deine Bemühungen! Ich habe das Skript für die neue Version 20.04.4 erstellt und sogar den 5.13er-Kernel angepasst. Schaus Dir bei Gelegenheit einfach mal an.

Sonnige Grüße
Christian

**Comment by Firefoxfan** [comment]
Hallo Christian,

ich habe micht getraut und kann Erfolg melden. Das neue Script läuft sehr gut (keinerlei M2-NVMes mehr trotz Updates ) und meine Anpassungen haben es auch nicht negativ verändert. Sehr gut. Ich kann zwar nicht erkennen welche "kleinen" Änderungen zu dem Erfolg geführt haben, doch es läuft einfach gut.

Ich habe aber noch eine Bitte. Ich habe die Generierung mit Umleitung des Fehlerprotokolls in eine Datei P2.txt durchgeführt (sudo ./ctbankix-lubuntu-20.04.4.sh >P1.txt 2>P2.txt). Wenn ich mir P2.txt ansehe, dann erscheinen darin einige "Fehlermeldung" deren Relevanz ich nicht beurteilen kann. Sie dir das (siehe Anhang) doch bitte mal an.

Hast du sehr gut hinbekommen.

Sonnige Grüße zurück
Werner
[P2.txt](https://github.com/ctbankix-continuation-team/ctbankix-continuation/files/8358045/P2.txt)
