### ISSUE TITLE
Moderne Hardware

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#6]
Meine neue Hardware:

MB: Asus Prime X570-Pro
Prozessor: AMD Ryzen 7 3700X
Grafikkarte: AMD Radeon RX570 8 GB
HDD: diverse
SSD: Samsung SSD 970 EVO Plus 250GB als M.2-Version!

Nach diversen Versuchen ist mit einem aktuellen BIOS Version 1005 endlich auch eine Generierung einer neuen, funktionsfähigen live.iso basierend auf Lubuntu 18.04.2 x64 mit den aktuellen Hardware-Erweiterungen (Version mit HWE) gelungen.

In der jetzt gelungenen Version gibt es nur 1 Problem. Die interne M.2-SSD wird immer noch erkannt und im Datei-Manager angezeigt. obwohl ja eigentlich alle Verbindungen zu den internen Festplatten gekappt sein sollten. Die übrigen HDDs werden nicht angezeigt. Damit wäre dann also auch eine Kommunikation zwischen meiner Windows-Umgebung (M.2-SSD ist Boot-Laufwerk) und meiner Bankix-Version möglich.

Wo ist die Generierungs-Prozedur anzupassen, damit das M.2-Laufwerk ebenfalls ausgeschlossen wird?

Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Werner,

bitte mal die 32Bit-Version verwenden. Dort sollte das M.2-Laufwerk ausgeschlossen werden. Ansonsten musst Du Dir einen eigenen 64-Bit-Kernel bauen.

VG, Christian!
