### ISSUE TITLE
Lubuntu 20.xx.xx LTS-Version Frühjahr 2020 

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#7]
Hallo ctBanker,

im Frühjahr (irgendwann demnächst also) soll ja wohl die neueste LTS-Version von Lubuntu Version 20.04.xx (?) erscheinen und dann wohl nur noch als 64-Bit-Version.

Hat schon mal jemand mit dieser neuen Version erfolgreich versucht ein ctBankix zu erzeugen?

Mir ist es jedenfalls nicht gelungen, doch ich weiß ja auch zu wenig von den Internas, wo man also die Prozedur anpassen müsste. Nur die Einrichtung der virtuellen Maschine lief einwandfrei.

Gruß und bleibt gesund
Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Werner,

ich habe eine Skript für die 64-Bit-Version im Repository bereitgestellt. Bitte gerne mit testen und mir die Fehler melden - Danke!

VG, Christian!

**Comment by Firefoxfan** [comment]
Hallo Christian,

leider nicht sehr erfolgreich. Diverse Mängel/fehlende Komponenten (siehe Fehler.txt und Protokoll.txt) Die erstellte live.iso kann nicht gebottet werden.
Gruß
Werner

[Fehler.txt](https://github.com/ctbankix-continuation-team/ctbankix-continuation/files/5045045/Fehler.txt)
[Protokoll.txt](https://github.com/ctbankix-continuation-team/ctbankix-continuation/files/5045046/Protokoll.txt)
