### ISSUE TITLE
Lubuntu 20.04.2 LTS Februar 2021

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#8]
Hallo,

das (geänderte) Script passend für Lubuntu 20.04.2 LTS hakt noch an einigen Stellen. Ich habe das alte Script angepasst, dort die Zeichenketten 20.04.1 durch 20.04.2 ersetzt.

Das Script läuft durch, generiert eine live.iso. Der Stick ist bootbar, aber Linux wird wg. fezhlender dateien nicht gestartet. Nach Umgeheung des Problems stell man fest, dass das neue CTBankix mit einem Kernel Version 5.4 statt 5.8 erstellt wurde.

Gruß
Werner

**Comment by eRaz3r** [comment]
Hallo Werner,

das alleinige anpassen der Zeichenkette wird nicht genügen. 

Ohne Werbung machen zu wollen, kann ich Dir meinen Fork ans Herz legen.

Grüße
Raz3r

**Comment by ctbankix-continuation-team** [comment]
Hallo Werner, hallo Raz3r,

Danke fuer Euren Enthusiasmus! Ich habe soeben eine neue Version fuer 20.04.2 bereitgestellt. Bitte testet Ihr nochmal und meldet mir eventuelle Fehler zurueck. Aufgrund des neuen Kernels (5.8) hatte ich wieder etwas Spass :-).

VG, Christian!
