### ISSUE TITLE
Lubuntu 20.04.2 Ergebnisse neues Script

### ISSUE THREAD

**Issue by Firefoxfan** [ctbankix-continuation-team/ctbankix-continuation#9]
Hallo Christian,

vielen Dank für dein Script. Ich habe es sofort mal ausprobiert und dazu noch folgende Hinweise:

    Bei der Zusammenstellung von Firefox wird immer noch die Erweiterung "https.everywhere ...." mit eingerichtet.
    Das ist meines Erachtens überflüssig, da die aktuellen FX-Versionen diese Funktion selbst enthalten.
    Konfigurierbar in den Einstellungen, Standard ist "Nicht aktiv".

    Während der Generierung wird folgender Hinweis angezeigt:

    Makefile.config:548: No sys/sdt.h found, no SDT events are defined, please install systemtap-sdt-devel or systemtap-sdt-dev
    Makefile.config:774: Python support disabled by user
    Makefile.config:887: No libzstd found, disables trace compression, please install libzstd-dev[el] and/or set LIBZSTD_DIR
    Makefile.config:966: No libbabeltrace found, disables 'perf data' CTF format support, please install libbabeltrace-dev[el]/libbabeltrace-ctf-dev
     
    Inwieweit das Auswirkungen auf das Endergebnis hat kann ich so nicht beurteilen. Diese Komponenten fehlen nach einer VM-Einrichtung
    (VirtualBox 6.1.18) einer Maschine mit der Version Lubuntu 20.04.2. Man kann sie zwar problemlos nachinstallieren, muss dann aber
    einen neuen Generierungslauf starten. Gibt es da eine Anpassungsmöglichkeit im Script?

    Ich habe die fehlenden Module nachinstalliert und eine neue Generierung laufen lassen, beide erstellten live.iso-Dateien sind gleich groß.

    In dem neuen ctbankix nehme ich einige Anpassungen vor (Firefox, Thunderbird, Atril, clamtk, Drucker) und installiere da auch den
    offiziellen Druckertreiber für meinen Canon PIXMA-TS705 von Canon. Aus Firefox heraus drucke ich dann gerne meine Kontoauszüge
    oder auch Überweisungsbelege. Dabei kann ich die Kontoauszüge, da sie als PDF-Dateien vorliegen, an Atril übergeben und dann ausdrucken.
    Überweisungen jedoch werden direkt aus der Bankanwendung heraus gedruckt, also über den in Firefox integrierten Druckvorgang.
    Dies führt immer zu einem Fehler in CUPS und es kann kein Ausdruck erfolgen. In Version 20.04.1 hat dieses Vorgehen noch problemlos
    geklappt. Wenn ich einen Ausdruck in eine PDF-Datei aus FX heraus erzeuge und diese dann mit Atril ausdrucke läuft alles problemlos.
    Auch der Ausdruck eines Testseite aus dem Druckereinstellungsmenü funktioniert einwandfrei.

    Leider funktioniert der Ausschluss der NVME-Laufwerke noch nicht richtig.
    1. Erstellung USB-Stick aus der live.iso und booten zeigt keine NVME-Laufwerke.
    2. Update dieser Version (4 Module im Zusammenhang mit Linux-Kernel) und anschleißende Anzeige der Laufwerke = keine NVMEs
    3. Erstellen Snapshot (problemlos) und danach reboot zeigt NVME-Laufwerke, jedoch nicht gemountet.

    Die neuen Kernel-Komponenten haben da wohl wieder etwas umgestellt.

Soweit mal meine ersten Erkenntnisse.

Mit winterlichem Gruß
Werner

**Comment by ctbankix-continuation-team** [comment]
Hallo Werner,

Danke fürs Ausprobieren und Posten. Ist das Problem mit dem NVME-Laufwerk noch aktuell? Falls ja, um welches Laufwerk (Hersteller, Modell, ...) handelt es sich?

Version 20.04.2 hat doch so einige Probleme gemacht. Ich überlege zukünftig nur noch die 1er-Version (also 20.04.1) zu unterstützen. Es ist doch jedes Mal einiges an Anpassungsarbeit zu tun. Klar, dadurch verlieren wir die Unterstützung neuerer Hardware aber ich glaube, dass es nur wenige gibt, die ctbankix nutzen.

Danke für Posten und viele Grüße
Christian
